/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  darkMode: "class",
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#e3c28a",
        "surface-dim": "#dbd9dc",
        "inverse-primary": "#b7c7eb",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#374765",
        "secondary-fixed": "#c9e6ff",
        "surface-container-high": "#eae7ea",
        "on-error": "#ffffff",
        "surface-container-low": "#f5f3f6",
        "primary-fixed-dim": "#b7c7eb",
        "on-primary-fixed": "#091b37",
        tertiary: "#211500",
        "inverse-on-surface": "#f2f0f3",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fbf8fb",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdea7",
        background: "#fbf8fb",
        "tertiary-container": "#3b2800",
        "primary-fixed": "#d7e2ff",
        "secondary-container": "#39b8fd",
        "on-secondary-fixed-variant": "#004c6e",
        surface: "#fbf8fb",
        "on-secondary-fixed": "#001e2f",
        secondary: "#006591",
        primary: "#041632",
        "on-background": "#1b1b1e",
        "primary-container": "#1b2b48",
        "surface-container": "#efedf0",
        "on-tertiary-container": "#ac8e5b",
        "on-secondary-container": "#004666",
        "secondary-fixed-dim": "#89ceff",
        "surface-variant": "#e4e2e5",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#271900",
        "on-primary-container": "#8393b5",
        "inverse-surface": "#303033",
        "outline": "#75777e",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#594317",
        "surface-tint": "#4f5e7e",
        "surface-container-highest": "#e4e2e5",
        "on-surface": "#1b1b1e",
        "on-surface-variant": "#44474d",
        "outline-variant": "#c5c6ce",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        base: "4px",
        gutter: "16px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
      },
      fontSize: {
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0px 4px 6px -1px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [],
};
